name: Nasa project CI
  on:
    push:
      branches: [ master ]
    pull-request:
      branches: [ master ]
  jobs:
    build:
    runs-on: ubuntu-latest
    steps:
        -uses: action/checkout@v2
        -uses: action/setup-node
         with:
            node-version: '16'
        -run: npm install
        -run: npm run build --prefix frontend

