on: push
name: Nasa project CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: 16.13.x
        - run: npm install
        - run: npm run build --prefix frontend

