on: push
name: Nasa project CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        -uses: actions/checkout@v2
        -name: use nodejs version 18
         uses: actions/setup-node@v2
         with:
           node-version: '18'
        -run: npm install
        -run: npm run build --prefix frontend

